# 1. 베이스 이미지
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive \
    VNC_PASSWORD=jaewoo \
    DISPLAY=:1 \
    VNC_GEOMETRY=1024x768 \
    VNC_DEPTH=24 \
    VNC_PORT=5901 \
    NOVNC_PORT=6081

# 2. 필수 패키지 설치
# RUN apt-get update && apt-get install -y \
#     python3 python3-pip python3-tk python3-dev \
#     tigervnc-standalone-server tightvncserver x11vnc xvfb \
#     xterm wmctrl x11-utils curl git \
#     nano vim net-tools build-essential \
#     libx11-dev libxext-dev libxtst-dev libxrender-dev libxt-dev \
#     dos2unix && \
#     rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends python3-venv\
    tigervnc-standalone-server tightvncserver \
    x11-xserver-utils \
    x11-utils \
    nano vim curl git \
    python3-pip python3-tk \
    python3-wxgtk4.0 \
    dos2unix && \
    rm -rf /var/lib/apt/lists/*

# 3. noVNC & websockify 설치
WORKDIR /opt
RUN git clone https://github.com/novnc/noVNC.git && \
    cd noVNC && git checkout v1.2.0 && \
    git clone https://github.com/novnc/websockify && \
    cd websockify && pip3 install . --break-system-packages

# 4. VNC 설정
RUN mkdir -p /root/.vnc && \
    printf "%s\n%s\nn\n" "$VNC_PASSWORD" "$VNC_PASSWORD" | vncpasswd

# 5. xstartup 설정
# RUN echo '#!/bin/bash\nxsetroot -solid grey\nwhile true; do sleep 1000; done\n' > /root/.vnc/xstartup && chmod +x /root/.vnc/xstartup
RUN printf '%s\n' \
    "#!/bin/bash" \
    "xsetroot -solid grey" \
    "xsetroot -cursor_name left_ptr" \
    "while true; do sleep 1000; done" \
    > /root/.vnc/xstartup && \
    chmod +x /root/.vnc/xstartup

# 6. 실행 스크립트 복사
COPY start.sh /opt/start.sh
RUN dos2unix /opt/start.sh && chmod +x /opt/start.sh

# 7. 포트 열기 (VNC, noVNC, CLI용 WebSocket용도 8001)
EXPOSE ${VNC_PORT} ${NOVNC_PORT}

# 8. 컨테이너 시작 시 스크립트 실행
CMD ["bash", "/opt/start.sh"]


# docker build -t webide-vnc .
# docker run -d --name vnc-webide -p 6081:6081 -e VNC_PORT=5901 -e NOVNC_PORT=6081 -e VNC_GEOMETRY=1024x1024 -e VNC_DEPTH=24 webide-vnc


# docker build -t webide-vnc .
# docker run -d -p 6081:6080 -p 10001:10007 -p 8001:8001 --name vnc-webide webide-vnc



##############################################################
# 서버 컴퓨터에서?
# # 1. 베이스 이미지
# FROM ubuntu:24.04

# ENV DEBIAN_FRONTEND=noninteractive \
#     VNC_PASSWORD=jaewoo \
#     DISPLAY=:1 \
#     VNC_GEOMETRY=1024x768 \
#     VNC_DEPTH=24

# # 2. universe 리포지토리 추가 + 필수 패키지 설치
# RUN apt-get update && apt-get install -y software-properties-common && \
#     add-apt-repository universe && apt-get update && \
#     apt-get install -y \
#     python3 python3-pip python3-tk python3-dev \
#     tigervnc-standalone-server x11vnc xvfb \
#     xterm wmctrl x11-utils curl git \
#     nano vim net-tools build-essential \
#     libx11-dev libxext-dev libxtst-dev libxrender-dev libxt-dev \
#     dos2unix && \
#     rm -rf /var/lib/apt/lists/*

# # 3. noVNC & websockify 설치
# WORKDIR /opt
# RUN git clone https://github.com/novnc/noVNC.git && \
#     cd noVNC && git checkout v1.2.0 && \
#     git clone https://github.com/novnc/websockify && \
#     cd websockify && pip3 install . --break-system-packages

# # 4. VNC 설정
# RUN mkdir -p /root/.vnc && \
#     printf "%s\n%s\nn\n" "$VNC_PASSWORD" "$VNC_PASSWORD" | vncpasswd

# # 5. xstartup 설정
# RUN echo '#!/bin/bash\nxsetroot -solid grey\nwhile true; do sleep 1000; done\n' > /root/.vnc/xstartup && chmod +x /root/.vnc/xstartup

# # 6. 실행 스크립트 복사
# COPY start.sh /opt/start.sh
# RUN dos2unix /opt/start.sh && chmod +x /opt/start.sh

# # 7. 포트 열기
# EXPOSE 10007 6080 8001

# # 8. 시작 명령
# CMD ["bash", "/opt/start.sh"]
