# 1. 베이스 이미지 설정
FROM python:3.10-slim

# 2. 작업 디렉토리 설정
WORKDIR /usr/src/app

# 3. 의존성 파일 복사 및 설치
COPY req.txt ./
RUN pip install --no-cache-dir -r req.txt

# 4. 소스코드 복사
COPY . .

# 5. FastAPI 서버 실행
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]